name: kedro39
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  # - python=3.10.12
  # - python=3.9.17
  # - pandas
  # - polars
  # - dask
  # - numpy
  # - numexpr
  # - matplotlib
  # - plotly
  # - openpyxl
  - conda-forge::kedro
  #  - kedro-neptune
  #  - kedro-airflow
  - pip
  - pip:
      - kedro-datasets
      - kedro-viz
      - find-kedro
      # - kedro-docker
      # - kedro-accelerator
      # - find-kedro
      # - kedro-mlflow